### ISSUE TITLE
Another EPIPE error on resize

### ISSUE THREAD

**Issue by cibulka** [scalableminds/gulp-gm#11]
Hello! 

I'm getting another EPIPE error with both `gulp-image-resize` and `gulp-gm`. Console output is a little different from https://github.com/scalableminds/gulp-gm/issues/8, so I'm opening a new issue. Here it goes:

```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: Error: write EPIPE
    at finish (/Users/Cibulka/Documents/Web/itvar.dev/node_modules/cibulka-gulp-tasks/node_modules/gulp-image-resize/node_modules/gulp-gm/index.js:40:21)
    at gm.<anonymous> (/Users/Cibulka/Documents/Web/itvar.dev/node_modules/cibulka-gulp-tasks/node_modules/gulp-image-resize/node_modules/async/lib/async.js:485:30)
    at gm.emit (events.js:118:17)
    at gm.<anonymous> (/Users/Cibulka/Documents/Web/itvar.dev/node_modules/cibulka-gulp-tasks/node_modules/gulp-image-resize/node_modules/gulp-gm/node_modules/gm/lib/getters.js:70:16)
    at Socket.cb (/Users/Cibulka/Documents/Web/itvar.dev/node_modules/cibulka-gulp-tasks/node_modules/gulp-image-resize/node_modules/gulp-gm/node_modules/gm/lib/command.js:318:16)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:107:17)
    at onwriteError (_stream_writable.js:317:10)
    at onwrite (_stream_writable.js:335:5)
    at WritableState.onwrite (_stream_writable.js:105:5)
```
The weird thing is that the plugin worked as expected untill yesterday. The only events that, I think, could affect the plugin was:

1) I ran `npm install` to check my NPM setup before project deployment.
2) I installed some missing Homebrew dependency because of `brew doctor` output. `libxml` it was? 

Any thoughts? Thank you!

**Comment by cibulka** [comment]
Also, if that helps, I use `gulp-imagemin` and from today, the tests for `gifsicle` and `optipng` started to fail - not on each `npm install`, but often.

**Comment by terryvi** [comment]
I am meeting the same question~

**Comment by msokk** [comment]
`gm` got updated along with a bug, which causes stream to close early.

https://github.com/aheckmann/gm/issues/448

**Comment by MadLittleMods** [comment]
@msokk :+1: updating to `gm@1.20.0` worked great :)

**Comment by normanrz** [comment]
I suppose doing `npm upgrade` should resolve this issue. Just tried it on my machine and the tests worked again.

**Comment by igorpronin** [comment]
Hallo, i have the same problem, using `gulp-image-resize`.

`events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Error: write EPIPE
    at finish (C:\_projects\zench-okm\node_modules\gulp-image-resize\node_modules\gulp-gm\index.js:40:21)
    at gm.<anonymous> (C:\_projects\zench-okm\node_modules\gulp-image-resize\node_modules\async\lib\async.js:485:30)
    at emitMany (events.js:108:13)
    at gm.emit (events.js:182:7)
    at gm.<anonymous> (C:\_projects\zench-okm\node_modules\gulp-image-resize\node_modules\gulp-gm\node_modules\gm\lib\getters.js:70:16)
    at Socket.cb (C:\_projects\zench-okm\node_modules\gulp-image-resize\node_modules\gulp-gm\node_modules\gm\lib\command.js:318:16)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at onwriteError (_stream_writable.js:304:10)`

Updating npm couldn't solve it.

**Comment by Scriptura** [comment]
Hello. same for me:
```
Starting 'imagesresize'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error in plugin 'gulp-gm'
Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%wx%h" "-" this most likely means the gm/convert binaries can't be found
  at finish (/Users/id/Documents/Project/node_modules/gulp-gm/index.js:40:21)
  at gm.<anonymous> (/Users/id/Documents/Project/node_modules/gulp-image-resize/node_modules/async/lib/async.js:485:30)
  at emitMany (events.js:108:13)
  at gm.emit (events.js:182:7)
  at gm.<anonymous> (/Users/id/Documents/Project/node_modules/gm/lib/getters.js:70:16)
  at cb (/Users/id/Documents/Project/node_modules/gm/lib/command.js:318:16)
  at ChildProcess.<anonymous> (/Users/id/Documents/Project/node_modules/gm/lib/command.js:231:9)
  at emitOne (events.js:77:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
  at onErrorNT (internal/child_process.js:344:16)
  at nextTickCallbackWith2Args (node.js:441:9)
  at process._tickCallback (node.js:355:17)
```

**Comment by OmarFaruque** [comment]
I also facing same problem using 'gulp-image'
showing error  Unhandled promise rejection (rejection id: 2): Error in plugin 'gulp-image'
