### ISSUE TITLE
Is Graphicmagick required when imageMagick=true ?

### ISSUE THREAD

**Issue by pawelmi** [scalableminds/gulp-gm#12]
My configuration:

var gulp = require('gulp');
	var gm = require('gulp-gm');
	gulp.task('example', function () {
	  gulp.src(conf.src.images)
	    .pipe(gm(function (gmfile) {
	    return gmfile.resize(100, 100);
	  }, {
	    imageMagick: true
	  }))
	    .pipe(gulp.dest('dist'));
	});

when I have only Imagemagick installed I have following error:

[ERROR] events.js:141
[ERROR]       throw er; // Unhandled 'error' event
[ERROR]       ^
[ERROR]
[ERROR] Error: write EPIPE
[ERROR]     at exports._errnoException (util.js:856:11)
[ERROR]     at Socket._writeGeneric (net.js:675:26)
[ERROR]     at Socket._write (net.js:694:8)
[ERROR]     at doWrite (_stream_writable.js:292:12)
[ERROR]     at writeOrBuffer (_stream_writable.js:278:5)
[ERROR]     at Socket.Writable.write (_stream_writable.js:207:11)
[ERROR]     at Socket.write (net.js:618:40)

when I have Graphicmagick and Imagemagick installed no error occurred.
Should I have GM and IM installed when I'm using imageMagick:true option ?

**Comment by piotr-cz** [comment]
It's not and it should not be listed as a [dependency in package.json](https://github.com/scalableminds/gulp-gm/blob/v0.0.8/package.json#L26), when you or me prefer to use ImageMagick.

Just like in [gulp-image-resize](https://github.com/scalableminds/gulp-image-resize).
