### ISSUE TITLE
write EPIPE error when using resize() function

### ISSUE THREAD

**Issue by jjsino** [scalableminds/gulp-gm#8]
Hello, I know there was an issue already closed about that.
But I'm still having the same problem when I try to resize png images.

'''
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:904:11)
    at Object.afterWrite (net.js:720:19)
'''

I've tried to reinstall gm, still not working.

Any hint, please?

**Comment by darrrk** [comment]
:+1: with big images
